### ISSUE TITLE
Promote skills and workshops

### ISSUE THREAD

**Issue by peterdesmet** [inbo/oscibio#55]
Promote the skills and workshops we can offer.

**Comment by peterdesmet** [comment]
@LienReyserhove @damianooldoni @milotictanja I don't think it is necessary to have this on our site. What do you think?

**Comment by milotictanja** [comment]
I think it is a lot of work to make a complete overview and keep it up to date. I'm not sure if it is worth it. The projects we work on and the outputs we deliver give an overview of our capabilities anyway...
