### ISSUE TITLE
Switch colours?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/oscibio#95]
## Current (left) vs more like inbo.be (right)

<img src="https://user-images.githubusercontent.com/600993/221211796-7e54981b-fdca-43fe-9ada-770149d30467.png" width="50%"><img src="https://user-images.githubusercontent.com/600993/221211851-d2103c07-200b-448f-b8c7-0762003df12b.png" width="50%">

**Comment by DimEvil** [comment]
For me the 'more link with INBO' is a slightly more attractive (imho)
