### ISSUE TITLE
Empty Twitter box on homepage

### ISSUE THREAD

**Issue by niconoe** [inbo/oscibio#99]
I guess it's due to recent Twitter/X API policy changes.

<img width="461" alt="Screenshot 2023-09-28 at 14 12 52" src="https://github.com/inbo/oscibio/assets/386387/a226a5f0-4279-40a9-b0ab-b93621953550">

**Comment by peterdesmet** [comment]
Indeed, although I still see something:

<img width="367" alt="Screenshot 2023-09-28 at 14 20 09" src="https://github.com/inbo/oscibio/assets/600993/bcdea5cc-3aaa-4f4b-9277-64ced7439908">

But would be good to just remove it, given the recent policies.
